name: ⏱ Update Safe Proposals

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:

jobs:
  update-proposals:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🔄 Update proposals.json
        run: |
          mkdir -p SAFE-Dashboard
          curl -s https://api.reown.com/proposals > SAFE-Dashboard/proposals.json

      - name: 📤 Commit & Push if Changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Update proposals.json (auto-sync)"
          file_pattern: SAFE-Dashboard/proposals.json
