name: 📘 Update Safe README + Telegram Alerts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🧠 Run Update Script
        run: npx ts-node scripts/updateReadme.ts
        env:
          SAFE_ADDRESS: ${{ secrets.SAFE_ADDRESS }}
          SAFE_CHAIN_ID: ${{ secrets.SAFE_CHAIN_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: 📝 Commit Updated README
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add README.md
          git commit -m '🔄 Auto-update README with Safe proposals [bot]'
          git push
        continue-on-error: true
