name: 🛡 Update Safe Info

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install deps
        run: npm ci

      - name: 🧠 Run script
        run: npx tsx scripts/fetch-safe-info.ts

      - name: 📤 Commit changes
        run: |
          git config user.name "SafeVault Bot"
          git config user.email "bot@safe-vault.xyz"
          git add README.md
          git commit -m "🔁 Auto-update Safe info" || echo "No changes"
          git push
