# .github/workflows/update-safe-info.yml
name: 🛡 Update Safe Info

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # Every 3 hours
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔐 Fetch Safe Info
        run: |
          npx tsx scripts/fetch-safe-info.ts

      - name: 📤 Commit updated README
        run: |
          git config --global user.name "SafeVault Bot"
          git config --global user.email "safe-bot@github.com"
          git add README.md
          git commit -m "🔄 Update Safe info [bot]" || echo "No changes to commit"
          git push
