name: Autofill PR Template

on:
  pull_request:
    types: [opened, edited]

jobs:
  autofill-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Fetch PR number
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const body = pr.data.body;
            const newBody = body
              .replace("<!-- AUTOFILL:commit_hash -->", `${{ steps.commit.outputs.hash }}`)
              .replace("<!-- AUTOFILL:vercel_preview_url -->", "https://safe-vault-f44t.vercel.app");

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: newBody,
            });
