# .github/workflows/ci.yml
name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  ci:
    uses: your-org/.github/.github/workflows/reusable-ci-node.yml@main
    with:
      node-version: "20"
