name: Reusable branch protection

on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: "main"

jobs:
  protect:
    runs-on: ubuntu-latest
    permissions:
      administration: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = "${{ inputs.branch }}";
            await github.rest.repos.updateBranchProtection({
              owner, repo, branch,
              required_status_checks: { strict: true, contexts: [] },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              required_linear_history: true,
              required_conversation_resolution: true
            });
