name: Mark stale issues and PRs

on:
  schedule:
    - cron: "0 3 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "work-in-progress"
          stale-issue-message: "This issue has been quiet for 30 days. Ping to keep it alive."
          stale-pr-message: "This PR has been quiet for 30 days. Ping to keep it alive."
