name: ⏳ Close stale issues

on:
  schedule:
    - cron: "0 0 * * *" # runs daily

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "⏳ This issue has been marked stale due to inactivity. It will be closed in 7 days unless updated."
          close-issue-message: "✅ Closing stale issue. Please reopen if this is still relevant."
          stale-issue-label: "stale"
